services:
  lst-depeg-bot:
    build: .
    container_name: lst-depeg-bot
    restart: unless-stopped
    env_file:
      - .env                # default env file
    environment:
      DATABASE_URL: file:/app/prisma/dev.db
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - ./prisma:/app/prisma