services:
  lst-depeg-bot:
    build: .
    container_name: lst-depeg-bot
    restart: unless-stopped
    env_file:
      - .env                # default env file
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}